---
development:
  cloud_name: arnaudb33
  api_key: '859127889119997'
  api_secret: "-gXRX5TVQud2Igv1vQJV9_CB_3o"
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: arnaudb33
  api_key: '859127889119997'
  api_secret: "-gXRX5TVQud2Igv1vQJV9_CB_3o"
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: arnaudb33
  api_key: '859127889119997'
  api_secret: "-gXRX5TVQud2Igv1vQJV9_CB_3o"
  enhance_image_tag: true
  static_image_support: false
